### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by beucismis** [beucismis/ozgursozluk#1]
- [ ] API endpoint
- [ ] Docker support
- [x] Page support for debe
- [ ] Author page and last entrys
- [ ] Optioanl displaying for pinned
- [x] Optional displaying author nickname
- [x] Sorthing for entries ~~today~~ and nice
- [ ] URL replace support for alternative front-ends (e.g: twitter to nitter)
